animations{
    enabled = no
}
monitor=eDP-1, 1920x1080@60.00Hz, auto, 1, bitdepth, 10
input {
    numlock_by_default = true
    follow_mouse = 1
    touchpad{
        natural_scroll = true 
    }
}
decoration{
    blur{
        enabled=yes
    }
}
xwayland{
    enabled = yes
}

bind = $mainMod, B, exec, alacritty -e bluetuith
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = udiskie
bind = $mainMod, V, exec, cliphist list | wofi -dmenu -display-columns 2 | cliphist decode | wl-copy
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
